server:
  compression:
    enabled: true
    
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      sensitive: false
  endpoint:
    health:
      show-details: always
      show-components: always
    prometheus:
      enabled: true

info:
  app:
    encoding: '@project.build.sourceEncoding@'
    java:
      source: '@java.version@'
      target: '@java.version@'

spring:
  main:
    allow-bean-definition-overriding: true
  project:
    version: '@project.version@'
    buildTimestamp: '@timestamp@'
  application:
    name: demo

logging.level.org.springframework.web.servlet.DispatcherServlet: DEBUG
